-- Generated by Oracle SQL Developer Data Modeler 3.3.0.734
--   at:        2013-04-03 19:58:30 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE Student CASCADE CONSTRAINTS 
;
DROP TABLE academic_info CASCADE CONSTRAINTS 
;
DROP TABLE country CASCADE CONSTRAINTS 
;
DROP TABLE immigration_info CASCADE CONSTRAINTS 
;
DROP TABLE programs CASCADE CONSTRAINTS 
;
DROP TABLE semester CASCADE CONSTRAINTS 
;
DROP TABLE student_semester_relation CASCADE CONSTRAINTS 
;
CREATE TABLE Student 
    ( 
     ut_eid VARCHAR2 (10 CHAR)  NOT NULL , 
     last_name VARCHAR2 (100 CHAR) , 
     first_name VARCHAR2 (100 CHAR) , 
     gender VARCHAR2 (1 CHAR) , 
     marital_status VARCHAR2 (1 CHAR) , 
     first_semester_enrolled NUMBER , 
     last_semester_enrolled NUMBER , 
     country_code NUMBER , 
     flex1 DATE , 
     flex2 NUMBER , 
     flex3 NUMBER , 
     flex4 VARCHAR2 (100 CHAR) , 
     flex5 VARCHAR2 (100 CHAR) , 
     flex6 VARCHAR2 (100 CHAR) 
    ) 
;



ALTER TABLE Student 
    ADD CONSTRAINT "Student PK" PRIMARY KEY ( ut_eid ) ;



CREATE TABLE academic_info 
    ( 
     major_code NUMBER  NOT NULL , 
     major_description VARCHAR2 (100 CHAR) , 
     school_code NUMBER , 
     school_name VARCHAR2 (200 CHAR) , 
     flex1 DATE , 
     flex2 NUMBER , 
     flex3 NUMBER , 
     flex4 VARCHAR2 (100 CHAR) , 
     flex5 VARCHAR2 (100 CHAR) , 
     flex6 VARCHAR2 (100 CHAR) 
    ) 
;



ALTER TABLE academic_info 
    ADD CONSTRAINT "academic_info PK" PRIMARY KEY ( major_code ) ;



CREATE TABLE country 
    ( 
     country_code NUMBER  NOT NULL , 
     country_name VARCHAR2 (100 CHAR) , 
     Region_of_citizenship VARCHAR2 (50 CHAR) , 
     region_code NUMBER , 
     flex1 DATE , 
     flex2 NUMBER , 
     flex3 NUMBER , 
     flex4 VARCHAR2 (100 CHAR) , 
     flex5 VARCHAR2 (100 CHAR) , 
     flex6 VARCHAR2 (100 CHAR) 
    ) 
;



ALTER TABLE country 
    ADD CONSTRAINT "country PK" PRIMARY KEY ( country_code ) ;



CREATE TABLE immigration_info 
    ( 
     visa_status_code NUMBER  NOT NULL , 
     visa_status_description VARCHAR2 (100 CHAR) , 
     flex1 DATE , 
     flex2 NUMBER , 
     flex3 NUMBER , 
     flex4 VARCHAR2 (100 CHAR) , 
     flex5 VARCHAR2 (100 CHAR) , 
     flex6 VARCHAR2 (100 CHAR) 
    ) 
;



ALTER TABLE immigration_info 
    ADD CONSTRAINT "immigration_info PK" PRIMARY KEY ( visa_status_code ) ;



CREATE TABLE programs 
    ( 
     program_code NUMBER  NOT NULL , 
     program_description VARCHAR2 (50 CHAR) , 
     flex1 DATE , 
     flex2 NUMBER , 
     flex3 NUMBER , 
     flex4 VARCHAR2 (100 CHAR) , 
     flex5 VARCHAR2 (100 CHAR) , 
     flex6 VARCHAR2 (100 CHAR) 
    ) 
;



ALTER TABLE programs 
    ADD CONSTRAINT "programs PK" PRIMARY KEY ( program_code ) ;



CREATE TABLE semester 
    ( 
     semester VARCHAR2 (10 CHAR)  NOT NULL , 
     year NUMBER  NOT NULL , 
     ut_eid VARCHAR2 (10 CHAR)  NOT NULL , 
     academic_level VARCHAR2 (2 CHAR) , 
     classification VARCHAR2 (10 CHAR) , 
     passport NUMBER , 
     visa_status_code NUMBER , 
     program_code NUMBER , 
     visa_status NUMBER , 
     major_code NUMBER , 
     major_code2 NUMBER , 
     flex1 DATE , 
     flex2 NUMBER , 
     flex3 NUMBER , 
     flex4 VARCHAR2 (100 CHAR) , 
     flex5 VARCHAR2 (100 CHAR) , 
     flex6 VARCHAR2 (100 CHAR) 
    ) 
;



ALTER TABLE semester 
    ADD CONSTRAINT "semester PK" PRIMARY KEY ( semester, year, ut_eid ) ;



CREATE TABLE student_semester_relation 
    ( 
     Student_ut_eid VARCHAR2 (10 CHAR)  NOT NULL , 
     semester_semester VARCHAR2 (10 CHAR)  NOT NULL , 
     semester_year NUMBER  NOT NULL , 
     semester_ut_eid VARCHAR2 (10 CHAR)  NOT NULL 
    ) 
;



ALTER TABLE student_semester_relation 
    ADD CONSTRAINT student_semester_relation__IDX PRIMARY KEY ( Student_ut_eid, semester_semester, semester_year, semester_ut_eid ) ;




ALTER TABLE student_semester_relation 
    ADD CONSTRAINT FK_ASS_5 FOREIGN KEY 
    ( 
     Student_ut_eid
    ) 
    REFERENCES Student 
    ( 
     ut_eid
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE student_semester_relation 
    ADD CONSTRAINT FK_ASS_6 FOREIGN KEY 
    ( 
     semester_semester,
     semester_year,
     semester_ut_eid
    ) 
    REFERENCES semester 
    ( 
     semester,
     year,
     ut_eid
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT program_semester_relation FOREIGN KEY 
    ( 
     program_code
    ) 
    REFERENCES programs 
    ( 
     program_code
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT school2_semester_relation FOREIGN KEY 
    ( 
     major_code2
    ) 
    REFERENCES academic_info 
    ( 
     major_code
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT school_semester_relation FOREIGN KEY 
    ( 
     major_code
    ) 
    REFERENCES academic_info 
    ( 
     major_code
    ) 
;


ALTER TABLE Student 
    ADD CONSTRAINT student_country_relation FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES country 
    ( 
     country_code
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT visa_semester_relation FOREIGN KEY 
    ( 
     visa_status
    ) 
    REFERENCES immigration_info 
    ( 
     visa_status_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
